.gitignore 파일 추가
eunbiiKim/ToDoApp-iOS pull request #18
Opened 2019-06-15 10:39 UTC by yejun614

.gitignore 파일을 추가했습니다.
gitignore.io 에서 swift, macos, xcode 키워드로 제작했습니다.

2019-06-16 02:43 UTC, jaemyeong approved these changes

2019-06-16 02:44 UTC, jaemyeong requested changes
두개의 커밋을 하나로 합쳐보세요

2019-06-16 02:54 UTC, yejun614 commented
커밋 두개 합쳤습니다.

git rebase -i HEAD~2 명령어를 통해서 마지막 커밋을 Squash 처리했고
git push origin docs/add-gitignore -f 를 통해서 원격저장소로 push 했습니다.

2019-06-26 06:11 UTC, jaemyeong approved these changes

2019-06-29 06:32 UTC, jaemyeong approved these changes

2019-06-29 06:33 UTC, merged